# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.CharField(max_length=30)),
                ('ureceive', models.CharField(max_length=20)),
                ('uaddr', models.CharField(max_length=100)),
                ('upostcode', models.CharField(max_length=6)),
                ('uphone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
